name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.16'
      - name: Build
        run: |
          go test -race ./...
          GOOS=linux GOARCH=amd64 go build -o droplake cmd/droplake-api/main.go